<?php include 'includes/page_top.php'; ?>
<main class="page-container">
    <h2>About</h2>
    <p>The Vāda Project is a platform for collaborative and reason- and evidence-sensitive debate that is built on a contemporary systematization of particular Indian theories of knowledge sources (<i>pramāṇa</i>) and methods of reasoning (<i>nyāya</i>). This systematization is most directly indebted to the theories and methods both of the Nyāya philosophy of <a href="https://en.wikipedia.org/wiki/Ny%C4%81ya_S%C5%ABtras"> Akṣapāda Gautama and his successors</a>, and of the Buddhist philosophy of <a href="https://plato.stanford.edu/entries/dharmakiirti/"> Dharmakīrti</a> and his successors. </p>
    <p>The purpose of a <i>vāda</i> debate is to arrive at knowledge (<i>pramā</i>) by resolving doubt through accredited <i>pramāṇa</i>s, in a way that is supplemented by philosophical argument (<i>tarka</i>). According to sūtra 1.1.23 of Gautama’s <i>Nyāya-Sutra</i>, “doubt (<i>saṃśaya</i>) is deliberative awareness in need of details about something particular” (Dasti and Phillips: 41). In other words, when doubt happens, there is awareness of a particular thing, but uncertainty about one or more properties located in it, or, to use another phrasing, there is uncertainty about the subject’s possession of one or more predicates. </p>
    <p>According to Uddyotakara’s commentary on <i>Nyāya-Sūtra </i>1.1.23, such uncertainty can happen within oneself or among two or more persons. Regardless, when there is doubt about a particular subject (p), such as a tall, thin thing perceived in the distance, both a thesis and at least one counter-thesis emerge. One might first think, “The tall, thin thing in the distance is a post” (Tp), and then think, “The tall, thin thing in the distance is a person” (Cp). Due to this uncertainty, one does not know how to proceed, and one’s actions are disrupted. The purpose of <i>vāda</i> is to resolve such doubts in ways that empower persons to attain ends they desire. </p>
    <p>As a platform for collaborative public deliberation, the Vāda Project especially seeks to help persons to resolve doubts produced from controversy (<i>vipratipratti</i>), which arises when persons voice contradictory judgments about particular subjects. As Uddyotakara writes in his commentary on <i>Nyāya-Sūtra</i> 1.1.23, “The cause of doubt that arises from controversy depends on there being speakers or advocates. ‘Which side is proposing the correct view and which is proposing the incorrect view?’ Such doubt arises for someone listening to the dispute” (Dasti and Phillips: 42). During the development of Indian theories and methods of <i>pramāṇa-vāda</i>, controversies about the existence or non-existence of enduring selves, the reliability and validity of the Vedas and Vedic injunctions, and the nature of causality, among other subjects, abounded. These controversies generated significant doubt, and as a result, persons’ actions were disrupted. “Should I adhere to Vedic prescriptions, or should I leave my household and meditate on the five aggregates?” The theoretical purpose of <i>vāda</i>, then, was to resolve such doubts in ways that would enable persons to achieve their desired ends. </p>
    <p>In contemporary times, too, actions can be stymied by doubts produced from public controversy. Through news networks, social media platforms, religious communities, university curricula and specialized publications, speakers and advocates articulate contradictory views about the same subjects. As a result, onlookers may not know which views are correct and which are incorrect, and action can be disrupted. The purpose of the Vāda Project platform is to resolve such doubts in ways that empower the public and its diverse members to attain desired ends. </p>
    <h3> Acknowledgements </h3>
    <p>The Vāda Project wishes to honor Akṣapāda Gautama, Dharmakīrti, Ratñakīrti, Bimal Krishna Matilal, Arindam Chakrabarti, Pradeep Gokhale, and Parimal Patil by striving toward, while expecting to fall short of, their standards of conciseness, clarity, wisdom, ingenuity, and practical concern.</p>
    <p>Further, the Vāda Project is grateful to the Norman J. Radow College of Humanities and Social Sciences and the Department of History and Philosophy at Kennesaw State University, which have provided generous financial and logistical support. </p>
</main>
<?php include 'includes/page_bottom.php'; ?>
